NAME = 'farfetch'
MAIN_SITE = 'https://www.farfetch.com'
OUTPUT_DIR = 'output'
FARFETCH_IMAGE_BASE_DIR = f'{OUTPUT_DIR}/images/farfetch'
FARFETCH_URLS = 'resources/farfetch_urls.csv'
SOLD_OUT_LABEL = 'Sold Out'
